apiVersion: v1
kind: Service
metadata:
    name: my-mysql
    labels:
        app: my-mysql
spec:
    type: NodePort
    ports:
        - nodePort: 3306
        - port: 3306
    selector:
        app: my-mysql
