apiVersion: v1
kind: Service
metadata:
    name: my-mysql
    labels:
        app: my-mysql
spec:
#    type: NodePort
    ports:
        - port: 3306
#          nodePort: 3306
    selector:
        app: my-mysql
