apiVersion: v1
kind: Service
metadata:
    name: ingress-nginx
    namespace: ingress-nginx
spec:
    externalIPs:
        - 172.26.187.116
        - 172.26.187.115
    ports:
        - name: http
          port: 80
          targetPort: 80
          protocol: TCP
        - name: https
          port: 443
          targetPort: 443
          protocol: TCP
    selector:
        app: ingress-nginx
