apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: user-ingress
    namespace: bupt-graduation-design
#    annotations:
#        nginx.ingress.kubernetes.io/rewrite-target: /
spec:
    rules:
        - host: www.debugya.cn
          http:
              paths:
                  - path: /user/
                    backend:
                        serviceName: user
                        servicePort: 8080
