apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: bupt-ingress
    namespace: bupt-graduation-design
    annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
    rules:
        - host: user.debugya.cn
          http:
              paths:
                  - path: /
                    backend:
                        serviceName: user
                        servicePort: 8080
